<a href="https://colab.research.google.com/github/HollyIrvine/Team_DataNinja7_Assignment1/blob/Team_DataNinja7_Assignment1/Individual_Analyses/DarrellSanson_Sales_Revenue_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%bigquery --project supple-design-465411-c1

                                                #ProfitBySegment 2019 - 2022

SELECT
  EXTRACT(YEAR FROM t1.order_date) AS order_year,
  t1.segment,
  SUM(t1.profit) AS total_profit
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  t1.order_date BETWEEN '2019-01-01' AND '2022-12-31'
GROUP BY order_year, t1.segment
ORDER BY order_year, t1.segment

Query is running:   0%|          |

Downloading:   0%|          |

    order_year      segment  total_profit
0         2019     Consumer    24319.8504
1         2019    Corporate    13513.2769
2         2019  Home Office    11710.8468
3         2020     Consumer    28460.1665
4         2020    Corporate    20688.3248
5         2020  Home Office    12470.1124
6         2021     Consumer    35770.9532
7         2021    Corporate    30995.1690
8         2021  Home Office    15029.0521
9         2022     Consumer    45568.2391
10        2022    Corporate    26782.3633
11        2022  Home Office    21088.6672

In [ ]:
%%bigquery --project supple-design-465411-c1

                                                #SalesByManufactor 2019 - 2023

SELECT
  t1.manufactory,
  EXTRACT(YEAR FROM t1.order_date) AS sales_year,
  SUM(t1.sales) AS total_sales
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
GROUP BY t1.manufactory, sales_year
ORDER BY t1.manufactory, sales_year;

Query is running:   0%|          |

Downloading:   0%|          |

            manufactory  sales_year  total_sales
0    3-ring staple pack        2019        5.640
1    3-ring staple pack        2020       16.920
2    3-ring staple pack        2021       10.528
3    3-ring staple pack        2022        9.024
4            3D Systems        2019     1299.990
..                  ...         ...          ...
689               Zebra        2021      988.641
690               Zebra        2022       42.560
691              iOttie        2019       39.980
692              iOttie        2021       55.972
693              iOttie        2022      343.828

[694 rows x 3 columns]

In [ ]:
%%bigquery --project supple-design-465411-c1

                                          #ProfitByManufactor 2019 - 2023

SELECT
  t1.manufactory,
  EXTRACT(YEAR FROM t1.order_date) AS sales_year,
  SUM(t1.profit) AS total_profit
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
GROUP BY t1.manufactory, sales_year
ORDER BY t1.manufactory, sales_year;

Query is running:   0%|          |

Downloading:   0%|          |

            manufactory  sales_year  total_profit
0    3-ring staple pack        2019        2.7072
1    3-ring staple pack        2020        7.1440
2    3-ring staple pack        2021        3.6848
3    3-ring staple pack        2022        3.1584
4            3D Systems        2019     -571.9956
..                  ...         ...           ...
689               Zebra        2021    -1046.3747
690               Zebra        2022       10.4576
691              iOttie        2019      -16.9915
692              iOttie        2021       -0.9995
693              iOttie        2022      -44.3778

[694 rows x 3 columns]

In [ ]:
%%bigquery --project supple-design-465411-c1

                                                #SalesBySegment 2019 - 2022

SELECT
  EXTRACT(YEAR FROM t1.order_date) AS order_year,
  t1.segment,
  SUM(t1.sales) AS total_sales
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  t1.order_date BETWEEN '2019-01-01' AND '2022-12-31'
GROUP BY order_year, t1.segment
ORDER BY order_year, t1.segment;

Query is running:   0%|          |

Downloading:   0%|          |

    order_year      segment  total_sales
0         2019     Consumer  266096.8126
1         2019    Corporate  128434.8737
2         2019  Home Office   89715.8118
3         2020     Consumer  266535.9333
4         2020    Corporate  128757.3069
5         2020  Home Office   75239.2688
6         2021     Consumer  296863.8992
7         2021    Corporate  207106.3618
8         2021  Home Office  105235.3370
9         2022     Consumer  331904.6999
10        2022    Corporate  241847.8244
11        2022  Home Office  159462.7309

In [ ]:
%%bigquery --project supple-design-465411-c1
                                              #Profit increase from 2019 to 2022 by Category
SELECT
  t1.category,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
      ELSE 0
    END) AS profit_2019,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.profit
      ELSE 0
    END) AS profit_2022,
  (SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.profit
      ELSE 0
    END) - SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
      ELSE 0
    END)) / SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
      ELSE 0
    END) * 100 AS profit_increase_percent
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  EXTRACT(YEAR FROM t1.order_date) IN (2019, 2022)
GROUP BY t1.category
HAVING SUM(
  CASE
    WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
    ELSE 0
  END) > 0
ORDER BY t1.category;

Query is running:   0%|          |

Downloading:   0%|          |

          category  profit_2019  profit_2022  profit_increase_percent
0        Furniture    5457.7255    3018.3913               -44.695069
1  Office Supplies   22593.4161   39736.6217                75.876997
2       Technology   21492.8325   50684.2566               135.819344

In [ ]:
%%bigquery --project supple-design-465411-c1
                                              #Profit increase from 2019 to 2022 by Region
SELECT
  t1.region,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
      ELSE 0
    END) AS profit_2019,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.profit
      ELSE 0
    END) AS profit_2022,
  (SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.profit
      ELSE 0
    END) - SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
      ELSE 0
    END)) / SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
      ELSE 0
    END) * 100 AS profit_increase_percent
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  EXTRACT(YEAR FROM t1.order_date) IN (2019, 2022)
GROUP BY t1.region
HAVING SUM(
  CASE
    WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.profit
    ELSE 0
  END) > 0
ORDER BY t1.region;

Query is running:   0%|          |

Downloading:   0%|          |

    region  profit_2019  profit_2022  profit_increase_percent
0  Central     539.5534    7550.8442              1299.461888
1     East   17059.6095   33230.5614                94.790868
2    South   11879.1200    8848.9079               -25.508725
3     West   20065.6912   43808.9561               118.327670

In [ ]:
%%bigquery --project supple-design-465411-c1
                                              #Sales increase from 2019 to 2022 By Category
SELECT
  t1.category,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END) AS sales_2019,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.sales
      ELSE 0
    END) AS sales_2022,
  (SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.sales
      ELSE 0
    END) - SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END)) / SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END) * 100 AS sales_increase_percent
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  EXTRACT(YEAR FROM t1.order_date) IN (2019, 2022)
GROUP BY t1.category
HAVING SUM(
  CASE
    WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
    ELSE 0
  END) > 0
ORDER BY t1.category;

Query is running:   0%|          |

Downloading:   0%|          |

          category   sales_2019   sales_2022  sales_increase_percent
0        Furniture  157192.8531  215387.2692               37.021032
1  Office Supplies  151776.4120  246097.1750               62.144547
2       Technology  175278.2330  271730.8110               55.028269

In [ ]:
%%bigquery --project supple-design-465411-c1
                                              #Sales increase from 2019 to 2022 By Region
SELECT
  t1.region,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END) AS sales_2019,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.sales
      ELSE 0
    END) AS sales_2022,
  (SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.sales
      ELSE 0
    END) - SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END)) / SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END) * 100 AS sales_increase_percent
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  EXTRACT(YEAR FROM t1.order_date) IN (2019, 2022)
GROUP BY t1.region
HAVING SUM(
  CASE
    WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
    ELSE 0
  END) > 0
ORDER BY t1.region;

Query is running:   0%|          |

Downloading:   0%|          |

    region   sales_2019   sales_2022  sales_increase_percent
0  Central  103838.1646  147098.1282               41.660948
1     East  128680.4570  213082.9040               65.590727
2    South  103845.8435  122905.8575               18.354142
3     West  147883.0330  250128.3655               69.139326

In [ ]:
%%bigquery --project supple-design-465411-c1
                                              #Sales increase from 2019 to 2022 By subCategory
SELECT
  t1.subcategory,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END) AS sales_2019,
  SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.sales
      ELSE 0
    END) AS sales_2022,
  (SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2022 THEN t1.sales
      ELSE 0
    END) - SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END)) / SUM(
    CASE
      WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
      ELSE 0
    END) * 100 AS sales_increase_percent
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
WHERE
  EXTRACT(YEAR FROM t1.order_date) IN (2019, 2022)
GROUP BY t1.subcategory
HAVING SUM(
  CASE
    WHEN EXTRACT(YEAR FROM t1.order_date) = 2019 THEN t1.sales
    ELSE 0
  END) > 0
ORDER BY t1.subcategory;

Query is running:   0%|          |

Downloading:   0%|          |

    subcategory  sales_2019   sales_2022  sales_increase_percent
0   Accessories  25014.2720   59946.2320              139.648118
1    Appliances  15313.6250   42926.9320              180.318553
2           Art   6057.9820    8863.0680               46.303967
3       Binders  43488.2650   72788.0450               67.373992
4     Bookcases  20036.6776   30024.2797               49.846598
5        Chairs  77241.5760   95554.3530               23.708446
6       Copiers  10849.7820   62899.3880              479.729510
7     Envelopes   3855.7500    3378.5740              -12.375699
8     Fasteners    661.3280     857.5940               29.677558
9   Furnishings  13826.2340   28915.0940              109.132104
10       Labels   2841.3940    3861.2160               35.891608
11     Machines  62023.3730   43544.6750              -29.793120
12        Paper  14834.9560   27694.7180               86.685542
13       Phones  77390.8060  105340.5160               36.115026
14      Storage  50329.0420   69677.6180               38.444157
15     Supplies  14394.0700   16049.4100               11.500152
16       Tables  46088.3655   60893.5425               32.123459

In [ ]:
%%bigquery --project supple-design-465411-c1
                                              #RankCityByYearSales
SELECT
  t1.region,
  t1.city,
  SUM(t1.sales) AS total_sales,
  RANK() OVER (
    ORDER BY SUM(t1.sales) DESC) AS sales_rank
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
GROUP BY t1.region, t1.city
ORDER BY sales_rank;

Query is running:   0%|          |

Downloading:   0%|          |

      region           city  total_sales  sales_rank
0       East  New York City   256368.161           1
1       West    Los Angeles   175851.341           2
2       West        Seattle   119540.742           3
3       West  San Francisco   112669.092           4
4       East   Philadelphia   109077.013           5
..       ...            ...          ...         ...
578    South   Ormond Beach        2.808         579
579    South      Pensacola        2.214         580
580    South        Jupiter        2.064         581
581     East         Elyria        1.824         582
582  Central        Abilene        1.392         583

[583 rows x 4 columns]

In [ ]:
%%bigquery --project supple-design-465411-c1
                                             #Total Profit by Region and Year
SELECT
  t1.region,
  EXTRACT(YEAR FROM t1.order_date) AS sales_year,
  SUM(t1.profit) AS total_profit
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
GROUP BY t1.region, sales_year
ORDER BY t1.region, sales_year;

Query is running:   0%|          |

Downloading:   0%|          |

     region  sales_year  total_profit
0   Central        2019      539.5534
1   Central        2020    11716.8020
2   Central        2021    19899.1629
3   Central        2022     7550.8442
4      East        2019    17059.6095
5      East        2020    21091.0130
6      East        2021    20141.5961
7      East        2022    33230.5614
8     South        2019    11879.1200
9     South        2020     8318.5940
10    South        2021    17702.8084
11    South        2022     8848.9079
12     West        2019    20065.6912
13     West        2020    20492.1947
14     West        2021    24051.6069
15     West        2022    43808.9561

In [ ]:
%%bigquery --project supple-design-465411-c1
                                            #Sales Total by Region and Year
SELECT
  t1.region,
  EXTRACT(YEAR FROM t1.order_date) AS sales_year,
  SUM(t1.sales) AS total_sales
FROM
  `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022 AS t1
GROUP BY t1.region, sales_year
ORDER BY t1.region, sales_year;

Query is running:   0%|          |

Downloading:   0%|          |

     region  sales_year  total_sales
0   Central        2019  103838.1646
1   Central        2020  102874.2220
2   Central        2021  147429.3760
3   Central        2022  147098.1282
4      East        2019  128680.4570
5      East        2020  156332.0570
6      East        2021  180685.8220
7      East        2022  213082.9040
8     South        2019  103845.8435
9     South        2020   71359.9805
10    South        2021   93610.2235
11    South        2022  122905.8575
12     West        2019  147883.0330
13     West        2020  139966.2495
14     West        2021  187480.1765
15     West        2022  250128.3655

In [ ]:
# Operations_analysts

#1.1 Regional Performance Summary (by Region)
#This query calculates total sales, total profit, profit margin, and order count per region.

%%bigquery --project supple-design-465411-c1

SELECT
    Region,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    -- Calculate Profit Margin: (Total Profit / Total Sales) * 100
    (SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0)) AS Profit_Margin_Percent,
    COUNT(DISTINCT Order_ID) AS Total_Orders
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    Region
ORDER BY
    Total_Sales DESC;

Query is running:   0%|          |

Downloading:   0%|          |

    Region  Total_Sales  Total_Profit  Profit_Margin_Percent  Total_Orders
0     West  725457.8245   108418.4489              14.944831          1611
1     East  678781.2400    91522.7800              13.483399          1401
2  Central  501239.8908    39706.3625               7.921629          1175
3    South  391721.9050    46749.4303              11.934342           822

In [ ]:
 # Operations_analysts

# 1.2 State-Level Performance (Top 10 by Sales)
# This query details sales, profit, and profit margin for each state,
# ordered by total sales to identify top-performing states.

%%bigquery --project supple-design-465411-c1
SELECT
    state, -- Changed from "State" to "state"
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) AS Profit_Margin_Percent,
    COUNT(DISTINCT order_id) AS Total_Orders
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    state
ORDER BY
    Total_Sales DESC
LIMIT 10; -- Adjust LIMIT as needed for more/ fewer states

Query is running:   0%|          |

Downloading:   0%|          |

,state,Total_Sales,Total_Profit,Profit_Margin_Percent,Total_Orders
0,California,457687.6315,76381.3871,16.688541,1021
1,New York,310876.2710,74038.5486,23.816082,562
2,Texas,170188.0458,-25729.3563,-15.118192,487
3,Washington,138641.2700,33402.6517,24.092863,256
4,Pennsylvania,116511.9140,-15559.9603,-13.354823,288
5,Florida,89473.7080,-3399.3017,-3.799219,200
6,Illinois,80166.1010,-12607.8870,-15.727205,276
7,Ohio,78258.1360,-16971.3766,-21.686405,236
8,Michigan,76269.6140,24463.1876,32.074618,117
9,Virginia,70636.7200,18597.9504,26.329012,115

In [ ]:
# Operations_analysts

#1.3 State-Level Performance (Bottom 10 by Profit Margin)
#This query identifies states with the lowest profit margins,
#which might indicate areas for consolidation or operational review.

%%bigquery --project supple-design-465411-c1
SELECT
    state,
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) AS Profit_Margin_Percent,
    COUNT(DISTINCT order_id) AS Total_Orders
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    state
HAVING
    SUM(sales) > 0 -- Exclude states with no sales to avoid division by zero issues
ORDER BY
    Profit_Margin_Percent ASC
LIMIT 10; -- Adjust LIMIT as needed

Query is running:   0%|          |

Downloading:   0%|          |

,state,Total_Sales,Total_Profit,Profit_Margin_Percent,Total_Orders
0,Ohio,78258.1360,-16971.3766,-21.686405,236
1,Colorado,32108.1180,-6527.8579,-20.330864,79
2,Tennessee,30661.8730,-5341.6936,-17.421289,91
3,Illinois,80166.1010,-12607.8870,-15.727205,276
4,Texas,170188.0458,-25729.3563,-15.118192,487
5,North Carolina,55603.1640,-7490.9122,-13.472097,136
6,Pennsylvania,116511.9140,-15559.9603,-13.354823,288
7,Arizona,35282.0010,-3427.9246,-9.715789,108
8,Oregon,17431.1500,-1190.4705,-6.829558,56
9,Florida,89473.7080,-3399.3017,-3.799219,200

In [ ]:
# Operations_analysts

#2.3 Performance by Product Category and Sub-Category
#This helps identify which product lines are contributing most to sales and profit,
#or which might be underperforming.


%%bigquery --project supple-design-465411-c1

SELECT
    category, -- Changed from "Category" to "category"
    subcategory, -- Changed from "Sub-Category" to "subcategory"
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) AS Profit_Margin_Percent,
    COUNT(DISTINCT order_id) AS Total_Orders
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    category,
    subcategory
ORDER BY
    Total_Profit DESC;

Query is running:   0%|          |

Downloading:   0%|          |

,category,subcategory,Total_Sales,Total_Profit,Profit_Margin_Percent,Total_Orders
0,Technology,Copiers,149528.0300,55617.8249,37.195585,68
1,Technology,Phones,330007.0540,44515.7306,13.489327,814
2,Technology,Accessories,167380.3180,41936.6357,25.054700,718
3,Office Supplies,Paper,78479.2060,34053.5693,43.391837,1191
4,Office Supplies,Binders,203412.7330,30221.7633,14.857361,1316
5,Furniture,Chairs,328449.1030,26590.1663,8.095673,576
6,Office Supplies,Storage,223843.6080,21278.8264,9.506113,777
7,Office Supplies,Appliances,107532.1610,18138.0054,16.867517,451
8,Furniture,Furnishings,91705.1640,13059.1436,14.240358,877
9,Office Supplies,Envelopes,16476.4020,6964.1767,42.267582,249
10,Office Supplies,Art,27118.7920,6527.7870,24.071083,731
11,Office Supplies,Labels,12486.3120,5546.2540,44.418672,346
12,Technology,Machines,189238.6310,3384.7569,1.788618,112
13,Office Supplies,Fasteners,3024.2800,949.5182,31.396504,215
14,Office Supplies,Supplies,46673.5380,-1189.0995,-2.547695,187
15,Furniture,Bookcases,114879.9963,-3472.5560,-3.022768,224
16,Furniture,Tables,206965.5320,-17725.4811,-8.564460,307

In [ ]:
# Operations_analysts

#FOCUS QUESTION 3: Where should we expand or consolidate?
#Required Analysis: Market opportunity identification


#3.1 States with High Sales but Low Profit (Potential for Consolidation/Efficiency Improvement)
#suggesting issues with costs, discounts, or operational inefficiencies.


%%bigquery --project supple-design-465411-c1

SELECT
    state,
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) AS Profit_Margin_Percent
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    state
HAVING
    SUM(sales) > 10000 -- Set a reasonable sales threshold to focus on significant markets
    AND (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) < 5 -- Example: Profit margin less than 5%
ORDER BY
    Profit_Margin_Percent ASC, Total_Sales DESC;

Query is running:   0%|          |

Downloading:   0%|          |

            state  Total_Sales  Total_Profit  Profit_Margin_Percent
0            Ohio   78258.1360   -16971.3766             -21.686405
1        Colorado   32108.1180    -6527.8579             -20.330864
2       Tennessee   30661.8730    -5341.6936             -17.421289
3        Illinois   80166.1010   -12607.8870             -15.727205
4           Texas  170188.0458   -25729.3563             -15.118192
5  North Carolina   55603.1640    -7490.9122             -13.472097
6    Pennsylvania  116511.9140   -15559.9603             -13.354823
7         Arizona   35282.0010    -3427.9246              -9.715789
8          Oregon   17431.1500    -1190.4705              -6.829558
9         Florida   89473.7080    -3399.3017              -3.799219

In [ ]:
# Operations_analysts

#3.2 States with High Profit and Good Sales (Potential for Expansion)
#These are the "star" areas where the business is performing well.
#Expansion efforts could yield good returns here.

%%bigquery --project supple-design-465411-c1

SELECT
    state,
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) AS Profit_Margin_Percent
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    state
HAVING
    SUM(sales) > 50000 -- Set a reasonable sales threshold for significant markets
    AND (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) > 15 -- Example: Profit margin greater than 15%
ORDER BY
    Profit_Margin_Percent DESC, Total_Sales DESC;

Query is running:   0%|          |

Downloading:   0%|          |

        state  Total_Sales  Total_Profit  Profit_Margin_Percent
0     Indiana   53555.3600    18382.9363              34.325110
1    Michigan   76269.6140    24463.1876              32.074618
2    Virginia   70636.7200    18597.9504              26.329012
3  Washington  138641.2700    33402.6517              24.092863
4    New York  310876.2710    74038.5486              23.816082
5  California  457687.6315    76381.3871              16.688541

In [ ]:

# Operations_analysts

#3.3 Identify Underperforming Product Categories/Sub-Categories in Specific Regions
#This query helps pinpoint specific product lines that are struggling in certain regions,
#indicating where consolidation or strategic changes might be needed.

%%bigquery --project supple-design-465411-c1


SELECT
    region,
    category,
    subcategory,
    SUM(sales) AS Total_Sales,
    SUM(profit) AS Total_Profit,
    (SUM(profit) * 100.0 / NULLIF(SUM(sales), 0)) AS Profit_Margin_Percent
FROM
    `supple-design-465411-c1`.Lab1_Eda3.Super_Store2019_2022
GROUP BY
    region,
    category,
    subcategory
HAVING
    SUM(sales) > 1000 -- Consider only categories with meaningful sales
    AND SUM(profit) < 0 -- Focus on categories that are losing money
ORDER BY
    Total_Profit ASC;

Query is running:   0%|          |

Downloading:   0%|          |

,region,category,subcategory,Total_Sales,Total_Profit,Profit_Margin_Percent
0,East,Furniture,Tables,39139.8070,-11025.3801,-28.169224
1,South,Furniture,Tables,43916.1920,-4623.0579,-10.527001
2,Central,Furniture,Furnishings,15254.3700,-3906.2168,-25.607198
3,Central,Furniture,Tables,39154.9710,-3559.6504,-9.091184
4,Central,Office Supplies,Appliances,23582.0330,-2638.6175,-11.189101
5,Central,Furniture,Bookcases,24157.1768,-1997.9043,-8.270438
6,West,Furniture,Bookcases,36004.1235,-1646.5117,-4.573120
7,Central,Technology,Machines,26797.3840,-1486.0666,-5.545566
8,South,Technology,Machines,53890.9600,-1438.8930,-2.670008
9,East,Furniture,Bookcases,43819.3340,-1167.6318,-2.664650
10,East,Office Supplies,Supplies,10760.1160,-1155.1352,-10.735342
11,Central,Office Supplies,Binders,56923.2820,-1043.6369,-1.833410
12,Central,Office Supplies,Supplies,9467.3720,-661.8881,-6.991255
13,West,Technology,Machines,42444.1220,-618.9264,-1.458215